---

image: python:3

before_script:
  - pip install --no-cache-dir poetry
  - poetry install

stages:
  - lint
  - test
  - build

lint:
  stage: lint
  script: make lint

test:
  stage: test
  script: make test

build:
  stage: build
  script: make build
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_TAG"
    paths:
      - dist/*.whl
      - dist/*.tar.gz
  only:
    - tags

...
