---

image: python:3

before_script:
  - pip install --no-cache-dir poetry
  - poetry install

stages:
  - lint
  - test

lint:
  stage: lint
  script: make lint

test:
  stage: test
  script: make test

...
